module.exports = {
  env: process.env.NODE_ENV,
  port: process.env.PORT || '3005',
  db_port: process.env.PORT || '5432',
  logs: process.env.NODE_ENV === 'production' ? 'combined' : 'dev',
  db_password: process.env.POSTGRES_PASSWORD || 'root',
  db_host: process.env.POSTGRESL_HOST || 'localhost',
  db_username: process.env.POSTGRES_USERNAME || 'andrii',
  db_name: process.env.POSTGRES_DATABASE || 'check-list',
  db_dialect: process.env.POSTGRES_DIALECT || 'postgres',
  jwt_key: process.env.JWT || 'NULP_ANDRII',
  aes_key: process.env.aes || 'NULP_ANDRII',
  build_origin: process.env.build_origin || 'chrome-extension://hilipakgbnkdfikcmccdlgonihbmbpea',
  dev_origin: process.env.dev_origin || 'http://localhost:3001',
};
